server:
  port: 8082
spring:
  application:
    name: order-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: orders
      port: 27017
      host: localhost
  kafka:
    bootstrap-servers: localhost:29092